### ISSUE TITLE
Implicit Serdes

### ISSUE THREAD

**Issue by maver1ck** [lightbend/kafka-streams-scala#46]
Please add option to use implicit Serdes in this library,
Similar to:
https://github.com/ogirardot/typesafe-kafka-streams

**Comment by debasishg** [comment]
We are having thoughts on this as we speak. There was already a PR (https://github.com/lightbend/kafka-streams-scala/pull/40) with implicit serdes. 

We are in the process of thinking through the use cases as the handling of Serdes from the top level APIs has changed a lot in Kafka Streams 1.0. There is now an abstraction `Serialized` which is used for handling serialization of key/values. And the APIs have 2 types of signatures, one that takes a `Serialized` and uses them. And the other that uses the default serializers. We are thinking of how to unify them with implicits without losing the ability to use the default serializers.

**Comment by maver1ck** [comment]
By default serializers you mean those from default.key.serde and default.value.serde options ?
The question is if we need them at all? Probably not.

**Comment by debasishg** [comment]
If u look at the APIs `KStream#groupByKey()` and `KStream#groupByKey(Serializable)`, the first one uses the default serializers while the second one uses the ones explicitly supplied. If we have implicit serializers and force the users to use them, then we lose out the first capability. Every time the user has to supply the serializers as implicit values. This is the topic we debated in the PR which I referenced earlier.

One option that we are thinking is to check the availability of the implicit values of the serializers and act accordingly .. if both serdes are available for key and value we use the second API, else use the first one.

WDYT ?

**Comment by maver1ck** [comment]
In the last question I just wanted to check if we're on the same page.

I'm thinking if using default serializers isn't equal to have them as implicit values ? 
(even better because if serializer type is wrong we'll get an error during compilation not in the runtime)

So current setting: 
```
config.put(StreamsConfig.DEFAULT_KEY_SERDE_CLASS_CONFIG, Serdes.String().getClass());
config.put(StreamsConfig.DEFAULT_VALUE_SERDE_CLASS_CONFIG, Serdes.String().getClass());
```
we change to:
implicit val stringSerde = Serdes.String()

**Comment by debasishg** [comment]
Indeed with implicits we have more type safety. The point is does this take away some feature from the underlying library ? We debated this as well in the PR. 

So you think it's ok to take away this feature of setting the defaults as part of config and handle with implicits ?

**Comment by maver1ck** [comment]
But having function with implicit gives possibility to set explicit values on the runtime.
The only difference will be that we'll be using Serdes instead of Produced.with etc.

**Comment by debasishg** [comment]
Yes, we can set explicit values with `Serde`s. We can replace all APIs that take `Serialized` with implicit Serdes. But possibly we may have to keep the ones that take `Produced` or `Consumed` (in addition to the new ones that take implicit Serdes) as these 2 allow setting of other values besides the serdes.

**Comment by maver1ck** [comment]
Sounds good.
So for groupBy we will have two definitions:
```
def groupBy(function)(implicit keySerde: K, valueSerde: V)
def groupBy(function, Serialized)
```

**Comment by debasishg** [comment]
We can debate if we need the second variant for `Serialized` if we have the first. But I think we need *both the variants* for functions that take `Produced` or `Consumed` as you can set other values besides the serdes with them.

**Comment by dhoepelman** [comment]
What about providing an opt-in implicit that uses the current runtime behavior?

```
implicit case object RuntimeSerialized extends Serialized[Nothing, Nothing] {
   // Either implement runtime lookup or throw unsupportedOperation
  ???
}

def through(topic: String)(implicit serialized: Serialized[K,V]): KStreamS[K, V] = {
  if(through == RuntimeSerialized)
    inner.through(topic)
  else
    inner.through(topic, serialized)
}
```

This way the default is the type-safe scala-style implicit API, with an opt-in per scope to use the less-overhead runtime behavior instead. The user will need to `import streams.RuntimeSerialized`

the principal is the same whether you use `Serde` or `Serialized` as the implicit

**Comment by debasishg** [comment]
@dhoepelman - this was the idea I was toying with to provide both the options .. see my remark below in one of the earlier comments ..

> One option that we are thinking is to check the availability of the implicit values of the serializers and act accordingly .. if both serdes are available for key and value we use the second API, else use the first one.

And you are correct that providing implicits on `Serialized` or `Produced` or `Consumed` calls for an easier implementation.

To everybody on this comment thread, how about the following strategy ..

1. we provide all implicits on `Serialized` or `Produced` or `Consumed` instead of `Serde`, because these are the preferred abstractions in Kafka Streams `1.0.0`
2. use the strategy mentioned by @dhoepelman to handle default serializers. The default strategy will be using the implicits (recommended) but if someone wants to use the config serializers, she can do that with a little more effort of an additional import. This also follows the principle of making the recommended way easier to use.

**Comment by maver1ck** [comment]
Ad 1)
But then we need to provide O(n^2) implicit values instead of O(n), where n = number of types.

**Comment by dhoepelman** [comment]
Agree with 1 and 2

@maver1ck 
The standard solution is to provide an implicit conversion (e.g. in [play-json](https://github.com/playframework/play-json/blob/397e42152d3b35f984b451f6733fe14d2dc346a8/play-json/shared/src/main/scala/play/api/libs/json/Format.scala#L75)) if there is a good default option
```scala
implicit def SerializedFromSerde[K,V](implicit keySerde: Serde[K], valueSerde: Serde[V]): Serialized[K,V] = Serialized.`with`(keySerde, valueSerde)
```

**Comment by debasishg** [comment]
@dhoepelman This one may be tricky ..
```scala
implicit case object ConfigSerialized extends Serialized[Nothing, Nothing] {
   //  throw UnsupportedOperationException in methods
}
```
`Serialized`'s constructor takes another `Serialized` and also the implicit match may not work because of (in)variance of Java type.

**Comment by debasishg** [comment]
I have started working on an implementation ..

**Comment by dhoepelman** [comment]
@debasishg right. Invariant is correct I think since a Serde is both a serializer and deserializer so we shouldn't change that.

Instead of a case object an implicit producer might work
```
implicit def configSerialized[K,V]: Serialized[K,V] = new ConfigSerialized[K,V]()
// Named class so we can check isInstanceOf[ConfigSerialized]
private[streams] ConfigSerialized[K,V]() extends Serialized[K,V](Serialized.`with`(null, null)) {}
```

But I don't know if this will cause weird things with implicit lookups or other problems...
I and my colleague @svroonland have some time to look into or help with an implementation February 16th

**Comment by debasishg** [comment]
How about the technique described in http://missingfaktor.blogspot.in/2013/12/optional-implicit-trick-in-scala.html ? It's a dressed up variant of the null check on the implicit. The advantage is that we can use this technique generically and NOT have to have specialized implementations for each of `Serialized`, `Produced` and `Consumed` ..

**Comment by dhoepelman** [comment]
I have difficulty seeing the advantage of `Perhaps` over providing a `null` default value for the implicit, but using a default `null`/`Perhaps for the implicit parameter is definitely a solution to support both behaviors.

Is it possible to provide an opt-in mechanism in this case?
Doing this by default is a bit dangerous because it transforms compile-time errors into run-time errors or might silently change run-time behavior.

**Comment by debasishg** [comment]
I agree regarding the transformation of compile time errors into run time errors. And as I already mentioned, it's a dress up over the null check pattern of implicits.

But it is possible to provide an opt-in mechanism with this technique as well .. Just an example I was trying out ..

The API implementation ..

```scala
def groupByKey(implicit serialized: Perhaps[Serialized[K, V]]): KGroupedStreamS[K, V] =
    serialized.fold[KGroupedStreamS[K, V]] { inner.groupByKey } { implicit ev => inner.groupByKey(ev) }
```

an implicit to convert the serdes into a `Serialized` ..

```scala
implicit def SerializedFromSerde[K,V](implicit keySerde: Serde[K], valueSerde: Serde[V]): Serialized[K,V] = 
    Serialized.`with`(keySerde, valueSerde)
```

and we can have the API usage with ..

```scala
implicit val stringSerde: Serde[String] = Serdes.String()
implicit val longSerde: Serde[Long] = Serdes.Long().asInstanceOf[Serde[Long]]
```

or ..

```scala
implicit val serialized = Serialized.`with`(stringSerde, longSerde)
```

or if we don't have the implicits in scope, the config values will be used, since in the above implementation `inner.groupByKey` will be called.

**Comment by debasishg** [comment]
I was also playing around with your suggestion ..

Here's the implicit for `Serialized` ..

```scala
implicit def configSerialized[K,V]: Serialized[K,V] = new ConfigSerialized[K,V]()

private[streams] class ConfigSerialized[K,V]() extends Serialized[K,V](Serialized.`with`(null, null)) {}
```

Here's the API implementation ..

```scala
def groupByKey(implicit serialized: Serialized[K, V]): KGroupedStreamS[K, V] =
  if (serialized.isInstanceOf[ConfigSerialized[K, V]]) inner.groupByKey
  else inner.groupByKey(serialized)
```

yeah .. that `isInstanceOf` (sort of) subverts the type system ..

Now the question is how do I include the implicit from serde to `Serialized` .. The moment I include the following in the `ImplicitConversions` object ..

```scala
implicit def SerializedFromSerde[K,V](implicit keySerde: Serde[K], valueSerde: Serde[V]): Serialized[K,V] = 
  Serialized.`with`(keySerde, valueSerde)
```

I get ambiguous implicits in lookup ..

**Comment by debasishg** [comment]
I have a [PR](https://github.com/lightbend/kafka-streams-scala/pull/47) on this, up for review ..

**Comment by debasishg** [comment]
Implicit Serdes now in `master` - closing this issue.
